sudo: required
language: c
notifications:
  email: false
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install gcc
  - sudo apt-get install gcovr
  - sudo apt-get install python3
  - sudo apt-get install python3-pip
  - wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
  - sudo unzip ninja-linux.zip -d /usr/local/bin/
  - sudo update-alternatives --install /usr/bin/ninja ninja /usr/local/bin/ninja 1 --force 
  - sudo pip3 install meson==0.44.0
  - sudo pip install codecov
  - sudo apt-get install doxygen
after_success:
  - bash <(curl -s https://codecov.io/bash)
script:
  - meson build -Db_coverage=true               # enable coverage
  - ninja -C build                              # build project
  - ninja test -C build                         # run tests
  - gcovr -r .                                  # report coverage
  - doxygen                                     # auto generate documentation
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "parof"
  - git config --local user.email "parolini.francesco.1@gmail.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  # auto updates the documentation
  on:
    branch: master

  provider: releases
  api_key: 
    secure: f895d0653acc430df0a37256ab922943b8c07247
  file_glob: true
  file: docs/*
  skip_cleanup: true
  overwrite: true

