sudo: required
language: c
notifications:
  email: false
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install gcc
  - sudo apt-get install gcovr
  - sudo apt-get install python3
  - sudo apt-get install python3-pip
  - wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
  - sudo unzip ninja-linux.zip -d /usr/local/bin/
  - sudo update-alternatives --install /usr/bin/ninja ninja /usr/local/bin/ninja 1 --force 
  - sudo pip3 install meson==0.44.0
  - sudo pip install codecov
  - sudo apt-get install doxygen
after_success:
  - bash <(curl -s https://codecov.io/bash)
script:
  - meson build -Db_coverage=true               # enable coverage
  - ninja -C build                              # build project
  - ninja test -C build                         # run tests
  - gcovr -r .                                  # report coverage
  - doxygen                                     # auto generate documentation
  - mv img/ftv2doc.png docs/html/
  - mv img/ftv2folderclosed.png docs/html/
  - mv img/ftv2folderopen.png docs/html/
before_deploy:
  - git config --local user.name "parof"
  - git config --local user.email "parolini.francesco.1@gmail.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: pages
  local-dir: docs/html
  skip-cleanup: true
  file_glob: true
  file: docs/*
  overwrite: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
