sudo: required
language: c
notifications:
  email: false
before_install:
- sudo apt-get update -qq
- sudo apt-get install gcc
- sudo apt-get install gcovr
- sudo apt-get install python3
- sudo apt-get install python3-pip
- wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
- sudo unzip ninja-linux.zip -d /usr/local/bin/
- sudo update-alternatives --install /usr/bin/ninja ninja /usr/local/bin/ninja 1 --force 
- sudo pip3 install meson==0.44.0
script:
- meson build -Db_coverage=true               # enable coverage
- ninja -C build                              # build project
- ninja test -C build                         # run tests
- gcovr -r .                                  # report coverage
- gcov build/src/src@@pilisp@sha/pilisp.c.o   # report with gcov
after_success:
- bash <(curl -s https://codecov.io/bash)   # report coverage